### ISSUE TITLE
remove py-mysqldb from DockerFile

### ISSUE THREAD

**Issue by rodolfosouza** [tcarreira/django-docker#1]
It is not required for the build and it is not supported by repository 

py-mysqldb --repository=http://dl-cdn.alpinelinux.org/alpine/v3.11/main (missing)

py-mysqldb --repository=http://dl-cdn.alpinelinux.org/alpine/v3.10/community (ok), but I removed from build and it works without 

Also fix Django version Django==3.0.3

**Comment by tcarreira** [comment]
Hi @rodolfosouza. Thank you for your help.

The py-mysqldb dependency was removed (c8a02448a88c9fbc1947a09ba02b4a5607d35c79).
I think it was some old dependency that I copied from another project. There is no need for it here.

Regarding Django version, I wrongly bumped its version to 1.1 instead of 1.0.2 or 1.0.3. Fixed in 3fded5cd13d910d3940afb076aa926ef21f13a50
